development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: device_development
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: device_test
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432